#!/usr/bin/env python  
#coding:utf-8  
'''
开始懂了
''' 

import sys, os
def qing():
    ''' qing note'''     # 紧邻函数写 
    print 'This qing'  
      
def ting():  
    ''' ting note'''
    print 'This ting'


  
print __name__      # __main__
print __doc__       # 开始懂了    内容描述即注释 必须进挨着文件 类 函数写，否则不生效
print qing.__doc__  # qing note
print ting.__doc__ # ting note
print __file__     #name_var.py  注： 不是绝对路径 同下
print sys.argv[0]  #name_var.py
print os.path.realpath(__file__)  #/Users/qingfeideyi/qing/demo/name_var.py

 (1).当"print os.path.dirname(__file__)"所在脚本是以完整路径被运行的， 那么将输出该脚本所在的完整路径，比如：

         python d:/pythonSrc/test/test.py

         那么将输出 d:/pythonSrc/test

 (2).当"print os.path.dirname(__file__)"所在脚本是以相对路径被运行的， 那么将输出空目录，比如：

         python test.py

         那么将输出空字符串


